name: Release app

on:
  push:
    branches:
      - '*alpha*'
      - '*beta*'
      - master

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-windows
          path: dist

      # - name: Download Linux Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: app-linux
      #     path: dist

      # - name: Download macOS Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: app-macos
      #     path: dist

      - name: Install dependencies and Run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            npm install --save-dev semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github conventional-changelog-conventionalcommits
            npx semantic-release --debug